CREATE TABLE bps_category (
    category_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(55) NOT NULL
);

CREATE TABLE bps_product (
    product_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    price       NUMBER(10,2) NOT NULL,
    category_id NUMBER NOT NULL,
    CONSTRAINT fk_product_product FOREIGN KEY ( category_id )
        REFERENCES bps_category (category_id )
);
